import numpy as np
import sys

args = sys.argv
file1 = args[1] 
file2 = args[2]
file3 = args[3]

stress = ['','','','']
for ifl,fname in enumerate([file1, file2, file3]):
    stress[ifl] = np.loadtxt(fname, dtype="float", comments="#",usecols=[0,1,2,3])
    #print(stress[ifl][0])

stress[3] = stress[0] - stress[1] - stress[2]
print(stress[3][0][0])
stress[3][:,0] *= -1.0
print(stress[3][0])

fname = 'water-PVA.xvg'
header=" This file is generated by calc_cross.py\n@ s0 legend \"Pres-XY\"\n@ s1 legend \"Pres-XZ\"\n@ s2 legend \"Pres-YZ\""
np.savetxt(fname, stress[3], fmt="%.6f", delimiter=" ", newline="\n", header=header,comments="#")
